### ISSUE TITLE
This project is not compatible with the latest API anymore

### ISSUE THREAD

**Issue by GigaDroid** [sipgate-io/io-labs-grafana-call-statistics#1]
Apparently this project is not compatible with the latest API anymore. Once I try to call /auth and try to sign in it leads me to `https://login.sipgate.com/auth/realms/sipgate-apps/protocol/openid-connect/auth?client_id=XXX%3Athird-party&redirect_uri=http%3A%2F%2F0.0.0.0%3A8080%2Fauth-code&response_type=code&scope=numbers%3Aread`,however the actual URL needs to be
`https://login.sipgate.com/auth/realms/third-party/protocol/openid-connect/auth?client_id=XXX%3Athird-party&response_type=code&scope=numbers%3Aread`. Even after fixing this URL there appear to be other API call causing bad request. Is this going to be updated?

**Comment by marsch** [comment]
any updates on this?

**Comment by Nils-AB** [comment]
Hey,
we majorly overhauled and updated the project, everything should work as expected again.
If you run into any more issues, please let us know!
